#!/usr/bin/sh
if [ -f /etc/profile.d/fzf.zsh ]; then
    source /etc/profile.d/fzf.zsh
fi


# Default: non-fuzzy search
export FZF_DEFAULT_OPTS='
  -e
  --color fg:252,bg:233,hl:67,fg+:252,bg+:235,hl+:81
  --color info:144,prompt:161,spinner:135,pointer:135,marker:118
  '

# If ag is available
if command -v ag >/dev/null 2>&1; then
  export FZF_DEFAULT_COMMAND='ag -l -g ""'
fi

# fe [FUZZY PATTERN] - Open the selected file with the default editor
#   - Bypass fuzzy finder if there's only one match (--select-1)
#   - Exit if there's no match (--exit-0)
fe() {
  local file
  file=$(fzf --query="$1" --select-1 --exit-0)
  [ -n "$file" ] && ${EDITOR:-vim} "$file"
}

# Modified version where you can press
#   - CTRL-O or Enter key to open with `open` command,
#   - CTRL-E to open with the $EDITOR
fo() {
  local out file key
  out=$(fzf-tmux --query="$1" --exit-0 --expect=ctrl-o,ctrl-e)
  key=$(head -1 <<< "$out")
  file=$(head -2 <<< "$out" | tail -1)
  if [ -n "$file" ]; then
    [ "$key" = ctrl-e ] && ${EDITOR:-vim} "$file" || xdg-open "$file"&
  fi
}

# fshow - git commit browser
fshow() {
  git rev-parse --git-dir > /dev/null 2>&1
  if [ $? -ne 0 ]; then
    return
  fi

  local out sha q
  while out=$(
      git log --decorate=short --graph --oneline --color=always |
      fzf-tmux --ansi --multi --no-sort --reverse --query=$q --print-query); do
    q=$(head -1 <<< "$out")
    while read sha; do
      [ -n "$sha" ] && git show --color=always $sha | less -R
    done < <(sed '1d;s/^[^a-z0-9]*//;/^$/d' <<< "$out" | awk '{print $1}')
  done
}

# fs [FUZZY PATTERN] - Select selected tmux session
#   - Bypass fuzzy finder if there's only one match (--select-1)
#   - Exit if there's no match (--exit-0)
fs() {
  local session
  session=$(tmux list-sessions -F "#{session_name}" | \
    fzf-tmux --query="$1" --select-1 --exit-0) &&
  tmux switch-client -t "$session"
}

# fh - repeat history, toggle sort with ctrl-r
fh() {
  print -z $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf-tmux +s -e --tac --toggle-sort=ctrl-r | sed 's/ *[0-9]*[\*]* *//')
  zle accept-line
}

# Override C-R
zle -N fh
bindkey '^r' fh

# TODO: check if still required
unalias j &>/dev/null
j() {
  if ! command -v fasd_cd >/dev/null 2>&1; then
    exit
  fi

  if [[ -z "$*" ]]; then
    cd "$(fasd_cd -d -l 2>&1 | sed -n 's/^[ 0-9.,]*//p' | fzf-tmux)"
  else
    fasd_cd -d "$@"
  fi
}

fmpc() {
  # if mpc is not available or mpd is not running
  if ! mpc -q status >/dev/null 2>&1; then
    return
  fi

  local song_position
  song_position=$(mpc -f "%position%) %artist% - %title%" playlist | \
    fzf-tmux --query="$1" --reverse --select-1 --exit-0 | \
    sed -n 's/^\([0-9]\+\)).*/\1/p')
  [ -n "$song_position" ] && mpc -q play $song_position
}
