source $HOME/.dotfiles/lib/utils.sh

# Default battery (used by i3blocks)
export BATTERY_ID=BAT1

if [ -n "$DISPLAY" ]; then
  # Load .Xresources (if any)
  [[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
  [[ -f ~/.config/xmodmap/conf ]] && xmodmap ~/.config/xmodmap/conf
fi

# run local .zprofile
source ~/.zprofile.local

if command_exists gpg-agent; then
  run_process gpg-agent --daemon &>/dev/null
fi

# load keychain to manage SSH and GPG keys
if command_exists keychain; then
  keychain --eval --agents ssh -Q --quiet id_rsa &>/dev/null
fi
