# -*- mode: sh -*-

export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# My aliases
alias make='nocorrect make'
alias mv='nocorrect mv'       # no spelling correction on mv
alias cp='nocorrect cp'       # no spelling correction on cp
alias mkdir='nocorrect mkdir' # no spelling correction on mkdir
alias m="nocorrect make -j3 -k"
alias v="valgrind --tool=memcheck --track-origins=yes  --show-reachable=yes --error-limit=no"
alias lf="ls -hltra"
alias cls='printf "\033c"' # clear screen

export ALTERNATE_EDITOR="" # Should start emacs --daemon if emacsclient runs without one.
alias e='emacsclient -t'
alias ec='emacsclient -c'

setopt autocd

# Don't print job information (e.g. fork pids)
set +m

# Enable ZSH colors
autoload colors
colors

# Unset shared history
#unsetopt share_history

if [[ -f ~/.tmuxinator/tmuxinator.zsh && $(command -v tmuxinator >/dev/null 2>&1) ]]; then
  source ~/.tmuxinator/tmuxinator.zsh
fi

if [ -f ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if command -v starship >/dev/null 2>&1; then
  export STARSHIP_CONFIG=~/.config/starship/starship.toml
  eval "$(starship init zsh)"
fi

if [[ -d  "${HOME}/.tmuxifier" && $(command -v tmuxifier >/dev/null 2>&1) ]]; then
  # Source tmuxifier
  eval "$(tmuxifier init -)"
  alias mux="tmuxifier"
fi

# Bindings
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
bindkey "^R" history-incremental-search-backward

fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

PATH="${HOME}/.cargo/bin:${PATH}"
if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init zsh)"
fi

# Source fzf after prezto with vi mode
if [ -f ~/.fzfrc ]; then
  source ~/.fzfrc
fi
